EpamTask.MyBlog.WebInterface/Controllers/SearchController.cs
namespace EpamTask.MyBlog.WebInterface.Controllers
{    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.UI;

    using EpamTask.MyBlog.Entities;
    using EpamTask.MyBlog.Logic;
    using log4net;
    using WebInterface.Models;

    public class SearchController : Controller
    {
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }

        public ActionResult SearchResults(List<BlogPostModel> posts)
        {
            try
            {
                return View(posts);
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }

        [ChildActionOnly]
        public ActionResult SearchPostsByTag()
        {
            try
            {
                SearchModel model = new SearchModel("Введите текст для поиска");
                return PartialView(model);
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchPostsByTagResults(SearchModel tag)
        {
            try
            {
                var model = SearchModel.SearchPostsByTag(tag.SearchText).ToList();

                if (model.Count != 0)
                {
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }

        [ChildActionOnly]
        public ActionResult SearchPostsByText()
        {
            try
            {
                SearchModel model = new SearchModel("Введите текст для поиска");
                return PartialView(model);
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchPostsByTextResults(SearchModel text)
        {
            try
            {
                var model = SearchModel.SearchPostsByText(text.SearchText).ToList();

                if (model.Count != 0)
                {
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                ILog logger = LogManager.GetLogger(typeof(SearchController));
                logger.Error(ex.Message.ToString(), ex);
                return View("Error.chtml");
            }
        }
    }
}

EpamTask.MyBlog.WebInterface/Views/Search/SearchPostsByTag.cshtml
@model EpamTask.MyBlog.WebInterface.Models.SearchModel

@using (Html.BeginForm("SearchPostsByTagResults", "Search", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal container-fluid">
        <h4>Поиск по тэгам:</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.SearchText)
                @Html.ValidationMessageFor(model => model.SearchText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Начать поиск" class="btn btn-default" />
            </div>
        </div>
    </div>
}

EpamTask.MyBlog.WebInterface/Views/Search/SearchPostsByTagResults.cshtml
@model IEnumerable<EpamTask.MyBlog.WebInterface.Models.BlogPostModel>

@{
    ViewBag.Title = "SearchPostsByTagResults";
}


<h2>Результаты поиска</h2>

<div class="container-fluid">
    <div class="col-xs-4">
        @Html.Action("SearchPostsByText", "Search")
        @Html.Action("SearchPostsByTag", "Search")
    </div>

    <div class="col-xs-8">
        <table class="table">
            <tr>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <div class="container-fluid">
                            @Html.HiddenFor(modelItem => item.PostID)
                            @Html.HiddenFor(modelItem => item.PostContent)
                            @Html.HiddenFor(modelItem => item.Privacy)

                            <div class="container-fluid">
                                <div class="col-xs-2">
                                    @Html.Action("ShowThumbnailAvatarOrDefault", "User", new { id = item.AuthorID })
                                </div>

                                <div class="col-xs-3">
                                    @Html.HiddenFor(modelItem => item.AuthorID)
                                    @Html.ActionLink(BlogUserModel.GetUser(item.AuthorID).BlogUserLogin, "Index", "Blog", new { userID = item.AuthorID }, null)
                                </div>

                                <div class="col-xs-3">
                                    @Html.DisplayFor(modelItem => item.PostCreationTime)
                                </div>

                                <div class="container-fluid">
                                    <div class="col-xs-8 pull-left">
                                        @Html.HiddenFor(modelItem => item.PostTitle)
                                        @Html.ActionLink(item.PostTitle, "PostAndComments", "Blog", new { postID = item.PostID }, null)
                                    </div>
                                </div>

                                <div class="container-fluid">
                                    <div class="col-xs-12 pull-left">
                                       @Html.Action("PostTags", "Blog", new { postID = item.PostID })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

EpamTask.MyBlog.WebInterface/Views/Search/SearchPostsByText.cshtml
@model EpamTask.MyBlog.WebInterface.Models.SearchModel

@using (Html.BeginForm("SearchPostsByTextResults", "Search", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal container-fluid">
        <h4>Поиск по тексту:</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.SearchText)
                @Html.ValidationMessageFor(model => model.SearchText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Начать поиск" class="btn btn-default" />
            </div>
        </div>
    </div>
}

EpamTask.MyBlog.WebInterface/Views/Search/SearchPostsByTextResults.cshtml
@model IEnumerable<EpamTask.MyBlog.WebInterface.Models.BlogPostModel>
@{
    ViewBag.Title = "SearchResults";
}

<h2>Результаты поиска</h2>

<div class="container-fluid">
    <div class="col-xs-4">
        @Html.Action("SearchPostsByText", "Search")
        @Html.Action("SearchPostsByTag", "Search")

    </div>

    <div class="col-xs-8">
        <table class="table">
            <tr>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <div class="container-fluid">
                            @Html.HiddenFor(modelItem => item.PostID)
                            @Html.HiddenFor(modelItem => item.PostContent)
                            @Html.HiddenFor(modelItem => item.Privacy)

                            <div class="container-fluid">
                                <div class="col-xs-2">
                                    @Html.Action("ShowThumbnailAvatarOrDefault", "User", new { id = item.AuthorID })
                                </div>

                                <div class="col-xs-3">
                                    @Html.HiddenFor(modelItem => item.AuthorID)
                                    @Html.ActionLink(BlogUserModel.GetUser(item.AuthorID).BlogUserLogin, "Index", "Blog", new { userID = item.AuthorID }, null)
                                </div>

                                <div class="col-xs-3">
                                    @Html.DisplayFor(modelItem => item.PostCreationTime)
                                </div>

                                <div class="container-fluid">
                                    <div class="col-xs-8 pull-left">
                                        @Html.HiddenFor(modelItem => item.PostTitle)
                                        @Html.ActionLink(item.PostTitle, "PostAndComments", "Blog", new { postID = item.PostID }, null)
                                    </div>
                                </div>

                            </div>

                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

EpamTask.MyBlog.WebInterface/Views/Search/SearchResults.cshtml
@model IEnumerable<EpamTask.MyBlog.WebInterface.Models.BlogPostModel>
@{
    ViewBag.Title = "SearchResults";
}

<h2>Результаты поиска</h2>

<div class="container-fluid">
    <div class="col-xs-4">
        @Html.Action("SearchPostsByText", "Search")
        @*@Html.Action("SearchPostsByTag", "Search")*@

    </div>

    <div class="col-xs-8">
        <table class="table">
            <tr>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <div class="container-fluid">
                            @Html.HiddenFor(modelItem => item.PostID)
                            @Html.HiddenFor(modelItem => item.PostContent)
                            @Html.HiddenFor(modelItem => item.Privacy)

                            <div class="container-fluid">
                                <div class="col-xs-2">
                                    @Html.Action("ShowThumbnailAvatarOrDefault", "User", new { id = item.AuthorID })
                                </div>

                                <div class="col-xs-3">
                                    @Html.HiddenFor(modelItem => item.AuthorID)
                                    @Html.ActionLink(BlogUserModel.GetUser(item.AuthorID).BlogUserLogin, "Index", "Blog", new { userID = item.AuthorID }, null)
                                </div>

                                <div class="col-xs-3">
                                    @Html.DisplayFor(modelItem => item.PostCreationTime)
                                </div>

                                <div class="container-fluid">
                                    <div class="col-xs-8 pull-left">
                                        @Html.HiddenFor(modelItem => item.PostTitle)
                                        @Html.ActionLink(item.PostTitle, "PostAndComments", "Blog", new { postID = item.PostID }, null)
                                    </div>
                                </div>

                            </div>

                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>